# https://taskfile.dev
version: "3"
tasks:
  default: cargo run
  # cargo run --package hello --bin hello
  test: cargo test
  build: cargo build --verbose
  clean: cargo clean
  install: cargo install --path .
