name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cargo build --verbose
          ls -al target
          cargo run 12 15
        working-directory: ./gcd
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./gcd
      - name: Run release
        run: |
          cargo build -r
          ls -al target/release
          tree target/release
        working-directory: ./gcd
